[Feature-14-DeleteContact-[Frontend]
biancanilsen/MyContacts pull request #14
Opened 2023-01-20 21:29 UTC by biancanilsen

2023-01-20 21:35 UTC, DavyCarvalho commented on src/frontend/src/app/confirm-dialog/confirm-dialog.component.html
> +  <h3 fxLayoutAlign="center center" matDialogTitle>{{ titleMessage }}</h3>
a escrita correta seria 'messageTitle', geralmente no inglês se escreve primeiro o sujeito, neste caso a Mensagem, e depois o atributo, nesse caso o Título, seguir esse raciocínio para outras variáveis e propriedades presentes no sistema

2023-01-20 21:35 UTC, DavyCarvalho commented on src/frontend/src/app/confirm-dialog/confirm-dialog.component.html
> +  <p>{{ subtitleMessage }}</p>
messageSubtitle*

2023-01-20 21:36 UTC, DavyCarvalho commented on src/frontend/src/app/confirm-dialog/confirm-dialog.component.ts
> +  public titleMessage: string = '';
corrigir nomes aqui também

2023-01-20 21:39 UTC, DavyCarvalho commented on src/frontend/src/app/pages/home/home.component.ts
> +
remover linha sobrando

2023-01-20 21:39 UTC, DavyCarvalho commented on src/frontend/src/app/pages/home/home.component.ts
> +                    let deleteDependent = await this.contactProvider.deleteContact(id);
verificar a necessidade dessa LET, caso nao seja necessária, remover a let e deixar apenas a chamada do endpoint

2023-01-20 21:40 UTC, DavyCarvalho commented on src/frontend/src/app/pages/login/login.component.html
> +        src="../../../assets/logo-teste.png"
está correta essa renomeação?

2023-01-20 21:42 UTC, DavyCarvalho commented on src/frontend/src/services/confirn-dialog.service.ts
> +import { Injectable } from '@angular/core';
corrigir nome do arquivo, confirM*

2023-01-20 21:42 UTC, DavyCarvalho requested changes
resolver comentários

2023-01-21 17:09 UTC, merged

2023-02-02 21:55 UTC, biancanilsen commented
![](https://github.trello.services/images/mini-trello-icon.png) [14 - [User Story] - Botão Excluir - Listagem de Contatos - [Frontend] - [Sprint: 4] - [Tamanho: P] - [Finalizado: 20/01]](https://trello.com/c/3NLIu0p9/17-14-user-story-bot%C3%A3o-excluir-listagem-de-contatos-frontend-sprint-4-tamanho-p-finalizado-20-01)

2023-02-02 21:56 UTC, biancanilsen commented
![](https://github.trello.services/images/mini-trello-icon.png) [14 - [Tech Story] - Débito Técnico - Cobertura de testes - [Frontend] - [Sprint: 5] - [Tamanho:] - [Finalizado:]](https://trello.com/c/qCjjQBcy/18-14-tech-story-d%C3%A9bito-t%C3%A9cnico-cobertura-de-testes-frontend-sprint-5-tamanho-finalizado)