[Feature-24-CreateNewUser-[Frontend]
biancanilsen/MyContacts pull request #15
Opened 2023-01-21 20:00 UTC by biancanilsen

2023-01-21 23:10 UTC, DavyCarvalho requested changes
resolver comentários

2023-01-21 23:10 UTC, DavyCarvalho commented on src/frontend/src/app/app.module.ts
> +
poderia remover essa linha sobrando

2023-01-21 23:10 UTC, DavyCarvalho commented on src/frontend/src/app/pages/login/login-dialog/login-dialog.component.scss
> +
remover linha sobrando

2023-01-21 23:10 UTC, DavyCarvalho commented on src/frontend/src/app/pages/login/login-dialog/login-dialog.component.spec.ts
> +describe('HomeDialogComponent', () => {
apenas um citação: esses arquivos de teste no momento são inúteis, porém não estou sugerindo apagar pq espero que vc os use pra fazer os testes desses components

2023-01-21 23:10 UTC, DavyCarvalho commented on src/frontend/src/app/pages/login/login-dialog/login-dialog.component.ts
> +      // id: this.data ? this.data.id : null,
remover comentário

2023-01-21 23:10 UTC, DavyCarvalho commented on src/frontend/src/app/pages/login/login.component.html
> -                  placeholder="Senha"
poderia manter o Senha como placeholder

2023-01-21 23:10 UTC, DavyCarvalho commented on src/frontend/src/app/pages/login/login.component.scss
> +
remover linha sobrando

2023-01-23 17:25 UTC, merged

2023-02-02 21:55 UTC, biancanilsen commented
![](https://github.trello.services/images/mini-trello-icon.png) [24 - [User Story] - Tela de Cadastro de Novo usuário - [Frontend] - [Sprint: 4] - [Tamanho: P] - [Finalizado: 22/01]](https://trello.com/c/uoMI8HXq/29-24-user-story-tela-de-cadastro-de-novo-usu%C3%A1rio-frontend-sprint-4-tamanho-p-finalizado-22-01)