[Feature-9-loginScreen]-[Frontend]
biancanilsen/MyContacts pull request #8
Opened 2023-01-18 19:18 UTC by biancanilsen

2023-01-18 19:43 UTC, DavyCarvalho requested changes

2023-01-18 19:43 UTC, DavyCarvalho commented on src/backend/index.js
> +console.log({
remover console.log

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/api-gateway.ts
> +      // this.cookieService.set('XSRF-TOKEN', 'eyJpdiI6IkQyWmtpZTBPempDOHgyZEQ5QmExVWc9PSIsInZhbHVlIjoiTFUwV1RSNlVvOWpoeFRRcHJieGFNZ3VaTTNsU3hQMDRZeVFyQndpYVFVSmVWM2lBOWRMaHZXM1k3cmt6WkpZNDZWb0QxSHpq
remover comentários

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/app/components/snack-bar/snack-bar.module.ts
> +
remover linhas sobrando

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/app/pages/home/home.component.html
> +<p>home works!</p>
verificar a necessidade deste arquivo com 1 linha

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/app/pages/login/login.component.scss
> +
apagar linha sobrando

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/app/pages/login/login.component.scss
> +
apagar linha

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/app/pages/login/login.component.scss
> +
apagar linha

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/app/pages/login/login.component.ts
> +
apagar linha

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/providers/auth.provider.ts
> +          // this.snackBar.successMessage(response.body.message);
apagar comentário

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/providers/user.provider.ts
> +            // this.snackBar.successMessage(response.body.message);
apagar comentário

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/services/user.service.ts
> +
apagar linha

2023-01-18 19:43 UTC, DavyCarvalho commented on src/frontend/src/styles.scss
> +
apagar linhas

2023-01-18 19:50 UTC, merged

2023-02-02 21:54 UTC, biancanilsen commented
![](https://github.trello.services/images/mini-trello-icon.png) [10 - [User Story] - Tela de Login - [Frontend] - [Sprint: 3] - [Tamanho: M] - [Finalizado: 18/01/]](https://trello.com/c/3KvtQ0C6/1-10-user-story-tela-de-login-frontend-sprint-3-tamanho-m-finalizado-18-01)